# Generated by Django 5.2.8 on 2025-11-19 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=20)),
                ('turno', models.CharField(max_length=20)),
                ('sala', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Estudante',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('nascimento', models.DateField()),
                ('ativo', models.BooleanField(verbose_name=True)),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportaprof.turma')),
            ],
        ),
    ]
