# Generated by Django 5.2.8 on 2025-11-23 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportaprof', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='estudante',
            name='ativo',
            field=models.BooleanField(verbose_name='Ativo'),
        ),
        migrations.CreateModel(
            name='TurmaDisciplina',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('disciplina_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reportaprof.disciplina')),
                ('professor_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reportaprof.professor')),
                ('turma_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reportaprof.turma')),
            ],
        ),
    ]
