# Generated by Django 5.2.8 on 2025-11-23 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportaprof', '0002_disciplina_professor_alter_estudante_ativo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Situacao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('situacao', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='estudante',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudantes', to='reportaprof.turma'),
        ),
        migrations.AlterField(
            model_name='turmadisciplina',
            name='disciplina_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turma_disciplinas', to='reportaprof.disciplina'),
        ),
        migrations.AlterField(
            model_name='turmadisciplina',
            name='professor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turma_disciplinas', to='reportaprof.professor'),
        ),
        migrations.AlterField(
            model_name='turmadisciplina',
            name='turma_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turma_disciplinas', to='reportaprof.turma'),
        ),
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_hora', models.DateTimeField(auto_now=True)),
                ('observacao', models.TextField(max_length=300)),
                ('alunos_id', models.ManyToManyField(related_name='ocorrencias', to='reportaprof.estudante')),
                ('professor_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ocorrencias', to='reportaprof.professor')),
                ('turma_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ocorrencias', to='reportaprof.turma')),
                ('situacao_id', models.ManyToManyField(related_name='ocorrencias', to='reportaprof.situacao')),
            ],
        ),
    ]
