# Generated by Django 5.2.8 on 2025-11-23 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportaprof', '0003_situacao_alter_estudante_turma_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ocorrencia',
            old_name='alunos_id',
            new_name='alunos',
        ),
        migrations.RenameField(
            model_name='ocorrencia',
            old_name='professor_id',
            new_name='professor',
        ),
        migrations.RenameField(
            model_name='ocorrencia',
            old_name='situacao_id',
            new_name='situacao',
        ),
        migrations.RenameField(
            model_name='ocorrencia',
            old_name='turma_id',
            new_name='turma',
        ),
        migrations.RenameField(
            model_name='turmadisciplina',
            old_name='disciplina_id',
            new_name='disciplina',
        ),
        migrations.RenameField(
            model_name='turmadisciplina',
            old_name='professor_id',
            new_name='professor',
        ),
        migrations.RenameField(
            model_name='turmadisciplina',
            old_name='turma_id',
            new_name='turma',
        ),
    ]
