# Generated by Django 5.2.8 on 2025-11-23 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportaprof', '0004_rename_alunos_id_ocorrencia_alunos_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ocorrencia',
            old_name='alunos',
            new_name='estudantes',
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='observacao',
            field=models.TextField(default='', max_length=300),
        ),
    ]
