# Generated by Django 5.2.8 on 2025-11-23 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportaprof', '0005_rename_alunos_ocorrencia_estudantes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocorrencia',
            name='observacao',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
