# Generated by Django 5.2.8 on 2025-11-23 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportaprof', '0006_alter_ocorrencia_observacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dependencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
    ]
