# Generated by Django 5.2.8 on 2025-11-23 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportaprof', '0007_dependencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocorrencia',
            name='dependencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Ocorrencia', to='reportaprof.dependencia'),
        ),
    ]
