# Generated by Django 5.2.8 on 2025-11-25 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportaprof', '0008_ocorrencia_dependencia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='situacao',
            old_name='situacao',
            new_name='nome',
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='dependencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ocorrencia', to='reportaprof.dependencia'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='estudantes',
            field=models.ManyToManyField(related_name='ocorrencia', to='reportaprof.estudante'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ocorrencia', to='reportaprof.professor'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='situacao',
            field=models.ManyToManyField(related_name='ocorrencia', to='reportaprof.situacao'),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ocorrencia', to='reportaprof.turma'),
        ),
    ]
